- name: Stop Docker Daemon
  hosts: pi
  tasks:
    - name: Make sure Docker is Stopped
      ansible.builtin.systemd:
        state: stopped
        name: docker
        scope: user
      # environment:
      #   XDG_RUNTIME_DIR: "/run/user/{{ myuid }}"