all:
  vars:
    ansible_python_interpreter: auto
  hosts:
    localhost:
      ansible_connection: local
  children:
    pi:
      hosts:
        pi@raspberrypi-[1:2]:
    swarm:
      children:
        manager:
          hosts:
            pi@raspberrypi-1:
        worker:
          hosts:
            pi@raspberrypi-2:
